/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 2000105
 */
public class Kanji_IA_UI extends javax.swing.JFrame {

    /**
     * Creates new form Kanji_IA_UI
     */
    public Kanji_IA_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        RadioButtonSL = new javax.swing.JRadioButton();
        RadioButtonHL = new javax.swing.JRadioButton();
        RadioButtonJoyoKanji = new javax.swing.JRadioButton();
        ButtonFlashcards = new javax.swing.JButton();
        ButtonPassages = new javax.swing.JButton();
        ButtonPassages1 = new javax.swing.JButton();
        LabelWelcome = new javax.swing.JLabel();
        jLabelBestLabelOpportunities = new javax.swing.JLabel();
        jLabelLearnJapanese = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(RadioButtonSL);
        RadioButtonSL.setText("Standard Level");

        buttonGroup1.add(RadioButtonHL);
        RadioButtonHL.setText("Higher Level");

        buttonGroup1.add(RadioButtonJoyoKanji);
        RadioButtonJoyoKanji.setText("Joyo Kanji");
        RadioButtonJoyoKanji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonJoyoKanjiActionPerformed(evt);
            }
        });

        ButtonFlashcards.setText("Flashcards");
        ButtonFlashcards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFlashcardsActionPerformed(evt);
            }
        });

        ButtonPassages.setText("Passages");

        ButtonPassages1.setText("Vocab List");
        ButtonPassages1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPassages1ActionPerformed(evt);
            }
        });

        LabelWelcome.setText("Welcome!");

        jLabelBestLabelOpportunities.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabelBestLabelOpportunities.setText("日本語学者");

        jLabelLearnJapanese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabelLearnJapanese.setText("Learn Japanese as if it's your native tongue");

        jMenuBar1.setBackground(new java.awt.Color(205, 235, 217));
        jMenuBar1.setAutoscrolls(true);

        jMenu1.setText("漢字");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Login");
        jMenu2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonSL)
                            .addComponent(ButtonFlashcards))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonHL)
                            .addComponent(ButtonPassages))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonPassages1)
                            .addComponent(RadioButtonJoyoKanji)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBestLabelOpportunities)
                            .addComponent(LabelWelcome)
                            .addComponent(jLabelLearnJapanese))))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(LabelWelcome)
                .addGap(32, 32, 32)
                .addComponent(jLabelBestLabelOpportunities, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLearnJapanese, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonFlashcards, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPassages, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPassages1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonSL)
                    .addComponent(RadioButtonHL)
                    .addComponent(RadioButtonJoyoKanji))
                .addGap(52, 52, 52))
        );

        RadioButtonSL.getAccessibleContext().setAccessibleName("RadioButtonSL");
        RadioButtonHL.getAccessibleContext().setAccessibleName("RadioButtonHL");
        RadioButtonHL.getAccessibleContext().setAccessibleDescription("");
        RadioButtonJoyoKanji.getAccessibleContext().setAccessibleName("RadioButtonJoyoKanji");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonJoyoKanjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonJoyoKanjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonJoyoKanjiActionPerformed

    private void ButtonFlashcardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFlashcardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonFlashcardsActionPerformed

    private void ButtonPassages1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPassages1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPassages1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kanji_IA_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kanji_IA_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kanji_IA_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kanji_IA_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kanji_IA_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFlashcards;
    private javax.swing.JButton ButtonPassages;
    private javax.swing.JButton ButtonPassages1;
    private javax.swing.JLabel LabelWelcome;
    private javax.swing.JRadioButton RadioButtonHL;
    private javax.swing.JRadioButton RadioButtonJoyoKanji;
    private javax.swing.JRadioButton RadioButtonSL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelBestLabelOpportunities;
    private javax.swing.JLabel jLabelLearnJapanese;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
