

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author 2000105
 */
public class Sign_Up extends javax.swing.JDialog {

    /**
     * Creates new form Sign_Up
     */
    // Initialising variables which each user is assigned
    public String username = "";
    public String password = "";
    public String level = "";
    public String language = "";
    public String passphrase = "";
    public String classCode = "";
    public boolean student = false;
    public boolean teacher = false;
    App main = App.getInstance();
    Serialiser serialiser = Serialiser.getInstance();
    
    public Sign_Up(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        String[] languages = {"English", "Japanese"};
        ComboBoxLanguage.setModel(new javax.swing.DefaultComboBoxModel(languages));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLogin = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuLogin1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TextFieldPassword = new javax.swing.JPasswordField();
        ButtonSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextFieldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RadioButtonSL = new javax.swing.JRadioButton();
        RadioButtonHL = new javax.swing.JRadioButton();
        RadioButtonJoyo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonTeacher = new javax.swing.JRadioButton();
        RadioButtonStudent = new javax.swing.JRadioButton();
        ComboBoxLanguage = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextFieldPassphrase = new javax.swing.JPasswordField();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuLogin2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        jMenuBar1.setBackground(new java.awt.Color(205, 235, 217));
        jMenuBar1.setAutoscrolls(true);

        jMenu1.setText("漢字");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenuLogin.setText("Login");
        jMenuLogin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuLogin.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuLoginMenuSelected(evt);
            }
        });
        jMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuLogin);

        jMenu4.setText("About");
        jMenu4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Sign Up");
        jMenu2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenuBar2.setBackground(new java.awt.Color(205, 235, 217));
        jMenuBar2.setAutoscrolls(true);

        jMenu3.setText("漢字");
        jMenu3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuBar2.add(jMenu3);

        jMenuLogin1.setText("Login");
        jMenuLogin1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuLogin1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuLogin1MenuSelected(evt);
            }
        });
        jMenuLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogin1ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenuLogin1);

        jMenu5.setText("About");
        jMenu5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Sign Up");
        jMenu6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SignUp");
        setName("SignUp"); // NOI18N

        TextFieldPassword.setText("jPasswordField1");

        ButtonSignUp.setText("Sign Up");
        ButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignUpActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        TextFieldUsername.setText("EdogawaVocab");

        jLabel2.setText("Password");

        buttonGroup2.add(RadioButtonSL);
        RadioButtonSL.setText("Standard Level");

        buttonGroup2.add(RadioButtonHL);
        RadioButtonHL.setText("Higher Level");

        buttonGroup2.add(RadioButtonJoyo);
        RadioButtonJoyo.setText("Joyo Kanji");

        jLabel3.setText("Level");

        jLabel4.setText("User type");

        buttonGroup1.add(jRadioButtonTeacher);
        jRadioButtonTeacher.setText("Teacher");

        buttonGroup1.add(RadioButtonStudent);
        RadioButtonStudent.setText("Student");

        ComboBoxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLanguageActionPerformed(evt);
            }
        });

        jLabel6.setText("Preferred Language");

        jLabel7.setText("Passphrase (if you forget password)");

        TextFieldPassphrase.setText("jPasswordField1");

        jMenuBar3.setBackground(new java.awt.Color(205, 235, 217));
        jMenuBar3.setAutoscrolls(true);

        jMenu7.setText("漢字");
        jMenu7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuBar3.add(jMenu7);

        jMenuLogin2.setText("Login");
        jMenuLogin2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenuLogin2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuLogin2MenuSelected(evt);
            }
        });
        jMenuLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogin2ActionPerformed(evt);
            }
        });
        jMenuBar3.add(jMenuLogin2);

        jMenu8.setText("About");
        jMenu8.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Sign Up");
        jMenu9.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jMenu9.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu9MenuSelected(evt);
            }
        });
        jMenuBar3.add(jMenu9);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(63, 63, 63)
                        .addComponent(TextFieldPassphrase, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(271, 271, 271))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(229, 229, 229)
                                .addComponent(ComboBoxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(TextFieldPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(68, 68, 68)
                                        .addComponent(RadioButtonStudent))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(48, 48, 48)
                                        .addComponent(RadioButtonSL)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RadioButtonHL)
                                    .addComponent(jRadioButtonTeacher))
                                .addGap(41, 41, 41)
                                .addComponent(RadioButtonJoyo)))
                        .addContainerGap(231, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonSL)
                    .addComponent(RadioButtonHL)
                    .addComponent(RadioButtonJoyo)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonTeacher)
                        .addComponent(RadioButtonStudent)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextFieldPassphrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignUpActionPerformed
        // TODO add your handling code here:
        // required to make the constructor in which the new user is held

        username = TextFieldUsername.getText();
        password = TextFieldPassword.getText();
        passphrase = TextFieldPassphrase.getText();
        language = ComboBoxLanguage.getSelectedItem().toString();
        // Originally each class was going to have a classcode through which
        // students could join, but this was scrapped do to a lack of necessity
  
        classCode = "000AAA";

        
        if (RadioButtonStudent.isSelected()){
            // checks if the new user is a teacher or a student
            student = true;
        }
        else{
            teacher = true;
        }
        
        // Set the students level to what he has indicated in the Sign Up form
        if (RadioButtonSL.isSelected()){
            level = "SL";
        }
        else if (RadioButtonHL.isSelected()){
            level = "HL";
        }
        else{
            level = "Joyo";
        }
        
        // Checks whether user is a student or teacher before creating new user
        if (teacher){
            Teacher x = createTeacher(username, password, passphrase, language, classCode);
            main.addTeacher(x);
            main.currentTeacher = x;
            main.currentStudent = null;
        }
        else if (student){
            Student x = createStudent(level, username, password, passphrase, language, classCode);
            main.addStudents(x);
            // adds student to the teacher's class
            (x.teacher).addStudentstoClass(x);
            main.currentStudent = x;
            // ensures there is only one user at a time, regardless of 
            // whether they are a student or teacher
            main.currentTeacher = null;
            setKanjiList(x);
        }
        
        // Changes language depending on what was set
        main.changeLocale(language);
        
        
        ExitSignUp(this);
        
        
    }//GEN-LAST:event_ButtonSignUpActionPerformed

    private void jMenuLoginMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuLoginMenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuLoginMenuSelected

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jMenuLogin1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuLogin1MenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuLogin1MenuSelected

    private void jMenuLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLogin1ActionPerformed

    private void jMenuLogin2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuLogin2MenuSelected
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jMenuLogin2MenuSelected

    private void jMenuLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogin2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuLogin2ActionPerformed

    private void ComboBoxLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxLanguageActionPerformed

    private void jMenu9MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu9MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MenuSelected
    
    private Teacher createTeacher(String username, String password, String passphrase, String language, String ClassCode){
        // Create filler classes that the Teacher can add people to
        ArrayList<Student> Class = new ArrayList<>();
        ArrayList<String> Curriculum = new ArrayList<>();
        
        return new Teacher(Class, Curriculum, username, password, passphrase, language, ClassCode);
    }
    
   private Student createStudent(String level, String username, String password, String passphrase, String language, String ClassCode){
       // Same concept as with Teacher, filler classes that the Student can add words to later
       ArrayList<Kanji> Kanji = new ArrayList<>();
       ArrayList<Word> VocabList = new ArrayList<>();
        
       Teacher x = main.findClass(ClassCode);
       return new Student(level, Kanji, VocabList, x, username, password, passphrase, language);
   }
   
   private void ExitSignUp(Sign_Up l){
       if (main.currentStudent != null){
           // Created file is tited off of the users username
           Serialiser.serialiseKanjiList(main.currentStudent.Kanji, (main.currentStudent.username + "_kanji_list.ser"));
           main.SerialiseStudents(main.Students, "All_Students.ser");
           main.SerialiseTeachers(main.Teacher, "All_Teachers.ser");
       }
       l.setVisible(false);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sign_Up dialog = new Sign_Up(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    private void setKanjiList(Student l) {
        // find the CSV file with all the Kanji
        String csvFile = "heisig-kanjis.csv";
        String delimiter = ",";
        // InputStream here simply opens the stream
        try (InputStream is = getClass().getClassLoader().getResourceAsStream(csvFile)) {
            // need to ensure that is isn't null and the csvFile is read
            if (is == null) {
                throw new FileNotFoundException("heisig-kanjis not found in classpath");
            }
            // Bufferring simply allows for incredible efficiency, 
            // reading thousands of lines at once
            try (BufferedReader br = new BufferedReader(new InputStreamReader(is))){
                String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(delimiter);

                // Makes sure that there is not too much data that errors are given
                if (data.length < 10) continue;

                // Create a new Kanji object
                Kanji kanji = new Kanji();
                kanji.setIndex(Integer.parseInt(data[2])); // Data[1] should always be an integer given the contents of the CSV
                kanji.setKanji(data[0]);
                kanji.setMeaning(data[3]);
                kanji.setKunyomi(data[7]);
                kanji.setOnyomi(data[6]);

                // Determine which list to add based on level
                // data[9] is basically a level set by the Japanese government
                // The reason it is not a variable is because this is its only instance
                if (l.level.equals("Joyo")) {
                    l.Kanji.add(kanji);
                } else if (l.level.equals("HL") && (data[9].equals("N5") ||
                        data[9].equals("N4") || data[9].equals("N3"))) {
                    l.Kanji.add(kanji);
                } else if (l.level.equals("SL") && (data[9].equals("N5") ||
                        data[9].equals("N4"))) {
                    l.Kanji.add(kanji);
                }
            }
            }
            
        } catch (IOException e) {
            // Catches like this were originally debugging tools that I frankly
            // Found from StackOverflow, but have been kept to ensure nothing goes
            // wrong
            e.printStackTrace();
        } catch (NumberFormatException e) {
            System.err.println("Error parsing integer from CSV: " + e.getMessage());
        }
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSignUp;
    private javax.swing.JComboBox<String> ComboBoxLanguage;
    private javax.swing.JRadioButton RadioButtonHL;
    private javax.swing.JRadioButton RadioButtonJoyo;
    private javax.swing.JRadioButton RadioButtonSL;
    private javax.swing.JRadioButton RadioButtonStudent;
    private javax.swing.JPasswordField TextFieldPassphrase;
    private javax.swing.JPasswordField TextFieldPassword;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JMenu jMenuLogin1;
    private javax.swing.JMenu jMenuLogin2;
    private javax.swing.JRadioButton jRadioButtonTeacher;
    // End of variables declaration//GEN-END:variables


}
